version: '3'
services:
  frontend-app:
    build:
      context: /comwell-frontend-main
    ports:
      - "3000:3000"
    depends_on:
      - backend-app

  backend-app:
    build:
      context: /comwell-backend-main
    ports:
      - "2000:2000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  python-script:
    build:
      context: /seed-db
      dockerfile: Dockerfile
    depends_on:
      - mongodb


